travis:
  secure:
    BINSTAR_TOKEN: mvCsWINfTVZ/hfR86GtPL4UySCaE5D0X8nk+eUytKCWndLnzm68gkcCHz7vgOkGzdbslIhM3g7xsmC0jlQN6K6tU0j1NsTZjdqGlY8l+Gz58fE0HzaQ9cKVN/voqnMq+zJVwumRXDYaJPR4il8/wsofs9sMqif5Ez527FqtcKInaGs5mLJXQze3bM/OJ+9wblFI0Oksw3yq/eoNF8pcmJHNQOuC66iDdp27iFNRgtxW0GkON5pwcCROZP/FB54F9yS7hCRQpEF3aDkIzx108pXLSzHMWqpFPXrnEqmVF/vOjdGaB8ona3ax0VgcLNHvgOlOdJZZEhxS+g5oEhh+yxUrQ1NJqjfFWR4V+A27bv9Hi69P7Z6flcdplhrzonevT/pZVK4txMJCbSH/uFtxR97Seanm7YBwuK3LkJ1WNIY89znZV3r1nG04kZYPqrBANZ3vElDA2u8cWN5ZDUE9ElIXO6env7/b7u+jbw9UY0Yk5KvBN1BwUlUzMTvc1HpTYsVVXGpyAaRdZ9la9cMNc86m+ZeO3kxWblDCkOid2PvyxzaWYFfNwYy7VlA9ot5ZmatQ0POijIgL1qEQdUXRV5lckF1JxaQlvBfazh3tMVcT1FiFrh6wE3QVKsdVh9up4VREsez0QrrVf2lUnsFluZKqHU5pr0BtHSk6r7h6G9uw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
